In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform

In [ ]:
uniform(10,50,(3,3))

array([[21.7219902 , 29.7145395 , 15.07801881],
       [42.7145865 , 35.89259847, 13.21583191],
       [35.22265205, 47.43340312, 49.11696808]])

Dataset

In [ ]:
data={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [ ]:
dataset=pd.DataFrame(data)

In [ ]:
dataset

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [ ]:
X=dataset.drop('Target',axis=1)
Y=dataset['Target']

In [ ]:
X

Day 1  Day 2  Day 3
0     30     40     50
1     40     50     20
2     50     20     15
3     20     15     60
4     15     60     70
5     60     70     50

In [ ]:
X_norm=Normalizer(norm='max').fit_transform(X)

In [ ]:
X_norm

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [ ]:
Y_norm=Normalizer(norm='max').fit_transform(np.reshape(array(Y),(1,-1)))

In [ ]:
Y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

ANN From Scratch

In [ ]:
 weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
 weight_2=array([[.5],[.1]])

In [ ]:
#shape 3 by 2
# weight_1=

In [ ]:
weight_1

array([[0.2, 0.1],
       [0.3, 0.1],
       [0.2, 0.1]])

In [ ]:
weight_2

array([[0.5],
       [0.1]])

In [ ]:
output1=X_norm[0]@weight_1
output1

array([0.56, 0.24])

In [ ]:
act_output=sigmoid(output1).numpy()
act_output

array([0.63645254, 0.55971365])

In [ ]:
pred_output=act_output@weight_2
pred_output

array([0.37419764])

Mean Squared Error

In [ ]:
y_true=Y_norm[0][0]
y_pred=pred_output

In [ ]:
y_true

0.2857142857142857

In [ ]:
mse(y_true,y_pred).numpy()

0.007829303112763407